server:
  port: 8081
spring:
  application:
    name: pharmacy
  profiles:
    active: local #prod #devel
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3307/pharmacy?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    url: jdbc:mariadb://localhost:3307
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true # data.sql 파일로 initialize 초기화 시키기 위해

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}
---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod